# Generated by Django 5.0.6 on 2024-06-03 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='playlist',
            name='movies',
            field=models.ManyToManyField(related_name='playlists', to='accounts.movie'),
        ),
    ]
