# Generated by Django 5.0.6 on 2024-06-03 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_movie_playlist_movies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='movies',
            field=models.ManyToManyField(to='accounts.movie'),
        ),
    ]
