# Generated by Django 5.0.6 on 2024-06-03 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_movie_description_alter_playlist_movies'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
